### ISSUE TITLE
Path mapping with ts-node

### ISSUE THREAD

**Issue by edufschmidt** [ef-carbon/tspm#14]
Any chance this also works in a setup involving ts-node? More specifically, I am thinking of a use case in which I don't have to transpile my codebase to js before running tspm.

**Comment by mattyclarkson** [comment]
I don't have familiarity with `ts-node` but do you mean for it to operate like a preprocessor or in-memory transpiler?

**Comment by edufschmidt** [comment]
Yes, that's what I had in mind :)

**Comment by mattyclarkson** [comment]
I want to get this in place, but haven't had the time yet. Not sure I'll have time to do it in the near future.

**Comment by cdagli** [comment]
@edufschmidt This should do that: https://github.com/dividab/tsconfig-paths

**Comment by mattyclarkson** [comment]
Looks like `tsconfig-paths` is a good solution. No need to reinvent the wheel.
