### ISSUE TITLE
pathMapping with structure from ./ does not work

### ISSUE THREAD

**Issue by rasmussyberg** [ef-carbon/tspm#25]
I cant seem to make it work when using rootDir       

my tsconfig.json looks like:

"outDir": "dist",
"rootDir": "./",       
"baseUrl": "./",   
"paths":{   
      "@GraphQL/entities/*":["lib/api/graphql/entities/*"],
},

my source is all in lib/

example 

lib/server.js

tsc builds as 

dist/lib/server.js

However the tool keeps giving the error:
File not found: '..../dist/server.js'
when it should look in '...../dist/lib/server.js'

**Comment by mattyclarkson** [comment]
What are your `include` and `exclude` keys in the `tsconfig.json`?

**Comment by cdagli** [comment]
Same thing happened to me as well. I could not debug the exact issue but creating a sibling folder e.g., 'test' to the source folder and placing a file in that test folder made it work properly. 

If you'd like to work on that I can create a repro

**Comment by mattyclarkson** [comment]
I think I know what this is, will look at it when I next circle around on this.

**Comment by dianjuar** [comment]
Didn't work in a [NestJs](https://nestjs.com) project

with the following Tsconfig file

`tsconfig.json`
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "paths": {
      "@common": ["src/common/index"],
      "@shared/*": ["src/shared/*"]
    }
  },
  "exclude": ["node_modules"]
}
```

`tsconfig.build.json`
```json
{
  "extends": "./tsconfig.json",
  "exclude": ["node_modules", "test", "**/*spec.ts"]
}
```
