### ISSUE TITLE
How to use it in watch mode?

### ISSUE THREAD

**Issue by eightHundreds** [ef-carbon/tspm#47]
```
tsc --watch
```

**Comment by eightHundreds** [comment]
```
        "watch": "tsc-watch -p ./ --onSuccess 'ef-tspm -s'",
```

**Comment by Jack-Barry** [comment]
If you want to avoid an extra dependency (which itself has 5 dependencies), you can also write a quick script like this:

```ts
import { exec } from 'child_process'

const child = exec('npx tsc --watch')

child.stdout?.on('data', chunk => {
  console.log(chunk)
  if (chunk.includes('Found 0 errors.')) exec('npx ef-tspm')
})
```

This isn't as full-featured as `tsc-watch` but for this scenario gets the job done. Haven't tested this code in particular, the one in our project is a little more robust but this is the gist of it.
