### ISSUE TITLE
How to specify a tsconfig file from the CLI?

### ISSUE THREAD

**Issue by StephenHaney** [ef-carbon/tspm#55]
I see that when using the library, you can specify an option to use a different tsconfig file. I'd like to use my `tsconfig.build.json` file when invoking ef-tspm from an npm script. Is that possible? Apologies if I missed it in the docs and thank you for the terrific library.

**Comment by mattyclarkson** [comment]
https://github.com/ef-carbon/tspm/blob/d003607c2e93b351fa1e9e8b51e616f7a750fd5b/lib/main.ts#L48

**Comment by StephenHaney** [comment]
Thanks @mattyclarkson
